<a href="https://colab.research.google.com/github/20KMJ/ESAA7/blob/main/0916.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CHAPTER 01** | 파이썬 기반의 머신러닝과 생태계 이해

# **01.** 머신러닝의 개념
***
* **머신러닝(Machine Learning)**은 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
* **머신러닝**은 데이터를 관통하는 패턴을 학습하고, 이에 기반한 예측을 수행함

## 머신러닝의 분류
* **지도학습**(Supervised Learning), **비지도학습**(Un-supervised Learning), **강화학습**(Reinforcement Learning)

> **지도학습**
* **분류**
* **회귀**
* 추천 시스템
* 시각/음성 감지/인지
* 텍스트 분석, NLP

> **비지도학습**
* 클러스터링
* 차원 축소
* 강화학습

## 데이터 전쟁
* 머신러닝의 가장큰 단점은 **데이터에 매우 의존적**이라는 것
* 앞으로 많은 회사의 경쟁력은 어떠한 품질의 데이터로 만든 머신러닝 모델이냐에 따라 결정될 수 있음

## 파이썬과 R 기반의 머신러닝 비교
* **R**은 통계 전용 프로그램 언어
* **파이썬**은 다양한 영억에서 사용되는 개발 전문 프로그램 언어
* 관심도는 **파이썬** > R
> * **쉽고 뛰어난 개발 생산성**으로 전 세계 개발들이 파이썬을 선호함. 특히 구글, 페이스북 등 유수의 IT 업계에서도 파이썬의 높은 생산성으로 인해 활용도가 매우 높음.
 * 오픈 소스 계열의 전폭적인 지원, 많은 라이브러리
 * 뛰어난 확장성, 유연성, 호환성
 * 머신러닝 애플리케이션과 결합한 다양한 **애플리케이션 개발** 가능
 * 엔터프라이즈 아키텍처로의 확장 및 마이크로서비스 기반의 실시간 연계 등 **다양한 기업 환경으로의 확산 가능**
 * 앞으로도 **딥러닝 프레임워크**는 파이썬을 중심으로 발전될 가능성이 큼

# **02.** 파이썬 머신러닝 생태계를 구성하는 주요 패키지
***
* **머신러닝 패키지**: 사이킷런(Scikit-Learn)
* **행렬/선형대수/통계 패키지**: 넘파이(Numpy), 사이파이(SciPy)
* **데이터 핸들링**: 판다스
* **시각화**: 맷플롯립(Matplotlib), 시본(Seaborn)

# **03.** 넘파이
***
* **넘파이(NumPy)**는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 빠른 배열 연산 속도
* 다양한 데이터 핸들링 기능 제공
* 통계 지원용 패키지를 직접 만드는 개발자가 아니라면 넘파이를 상세하게 알 필요는 없으나, 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요함

## 넘파이 ndarray 개요

In [ ]:
# 넘파이 모듈 임포트하기
import numpy as np

* `as np`를 추가해 약어로 모듈을 표현해주는 게 관례
* 넘파이 기반 데이터 타입은 ndarray임. **ndarray**를 이용해 넘파이에서 다차원(Multi-dimension) 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음.

In [ ]:
array1 = np.array([1, 2, 3])           # 리스트 [ ]는 1차원
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [ ]:
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [ ]:
array3 = np.array([[1, 2, 3]])         # 리스트의 리스트 [[ ]]는 2차원
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
# 각 array의 차원을 ndarray.ndim 이용해 확인하기
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


## ndarray의 데이터 타입

> **list** vs **array**
* list는 서로 다른 데이터 타입을 가질 수 있으나, array는 같은 데이터 타입만 가능
* list는 내부 배열에서 원소 개소가 달라도 되나, array는 내부 배열 내 원소 개수가 모두 같아야 함
* 연산 차이 ex) array는 [1, 2] + [3, 4] = [4, 6] 이고 list는 [1, 2, 3, 4] 임
* 수치 계산이 많고 복잡할 때나 행렬같은 다차원 배열을 쓸 때는 **array**를 사용함

In [ ]:
list1 = [1, 2, 3]
print(type(list1))

<class 'list'>


In [ ]:
array1 = np.array(list1)
print(type(array1))

<class 'numpy.ndarray'>


In [ ]:
# ndarray내의 데이터 타입은 dtype 속성으로 확인 가능
print(array1, array1.dtype)

[1 2 3] int64


In [ ]:
# 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하는 경우의 형 변환
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U21


In [ ]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [ ]:
# ndarray 내 데이터값의 타입 변경은 astype( ) 메서드 이용
# int32 -> float64 -> int32
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1. 2. 3.] float64
[1 2 3] int32


In [ ]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


## ndarray를 편리하게 생성하기 - `arrange`, `zeros`, `ones`
* **테스트용**으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 **초기화**해야 할 경우에 사용

In [ ]:
# arrage()
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
# zeros()
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [ ]:
# ones()
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 변경하는 `reshape( )`

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# -1 인자는 알맞는 shape으로 자동 변환

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


> **reshape(-1,1)**  
> 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장함

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())   # tolist() 메서드를 이용해 리스트 자료형으로 변환

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [ ]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [ ]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
1. 특정한 데이터만 추출
2. 슬라이싱(Slicing): 연속된 인덱스상의 ndarray 추출
3. 팬시 인덱싱(Fancy Indexing)
4. 불린 인덱싱(Boolean Indexing): True에 해당하는 데이터의 ndarray 반환

> **단일 값 추출**

In [ ]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


* `array1[2]`의 타입은 더 이상 ndarray 타입이 아니고 ndarray 내의 데이터값을 의미

In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [ ]:
# 데이터 수정
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
# 다차원 ndarray에서 단일 값 추출하기
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


> **슬라이싱**

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 ndarray 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[0:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [ ]:
print('array2d:\n',array2d)
print('array2d[0]:\n',array2d[0])
print('array2d[1]:\n',array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0]:
 [1 2 3]
array2d[1]:
 [4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환함

> **팬시 인덱싱**

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

array3 = array2d[[0, 1], 2]     # (0,2), (1,2)
print('array3:\n', array3)

array4 = array2d[[0, 1], 0:2]   # ((0,0),(0,1)), ((1,0),(1,1))
print('array4:\n', array4)

array5 = array2d[[0, 1]]        # ((0,:),(1,:))
print('array5:\n', array5)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array3:
 [3 6]
array4:
 [[1 2]
 [4 5]]
array5:
 [[1 2 3]
 [4 5 6]]


> **불린 인덱싱**
* **조건 필터링** & **검색** 동시 가능

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [ ]:
# 불린 인덱싱 과정 이해하기
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [ ]:
# 직접 인덱스 집합을 만들어 대입한 것과 동일
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


## 행렬의 정렬 - `sort()`와 `argsort()`

> **행렬 정렬**

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print(org_array)

# np.sort()로 정렬
# 원 행렬 유지
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]


In [ ]:
# ndarray.sort()로 정렬
# 원 행렬 변환
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [ ]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [ ]:
# 행렬이 2차원 이상일 경우
# axis 축 값 설정하기
array2d = np.array([[8, 12],
                    [7, 1 ]])
print('원 행렬:\n', array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

원 행렬:
 [[ 8 12]
 [ 7  1]]
로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


> **정렬된 행렬의 인덱스를 반환하기**: `np.argsort()`

* 넘파이의 데이터 추출에서 많이 사용됨

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print(org_array)

sort_indices = np.argsort(org_array)
print(sort_indices)
print(org_array[sort_indices])
print(type(sort_indices))

[3 1 9 5]
[1 0 3 2]
[1 3 5 9]
<class 'numpy.ndarray'>


In [ ]:
# 내림차순
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(org_array)
print(sort_indices_desc)
print(org_array[sort_indices_desc])

[3 1 9 5]
[2 3 0 1]
[9 5 3 1]


In [ ]:
# 사용 예시
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(np.sort(score_array))
print(name_array[sort_indices_asc])

[78 84 88 95 98]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기
> **행렬 내적(행렬 곱)** : `np.dot()`

In [ ]:
A = np.array( [[1, 2, 3],
               [4, 5, 6]])

B = np.array( [[7, 8],
               [9, 10],
               [11, 12]])

dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


> **전치 행렬**: `np.transpose()`

In [ ]:
A = np.array([[1, 2],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A trnaspose:\n', transpose_mat)

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print('B transpose:\n', np.transpose(B))

A trnaspose:
 [[1 3]
 [2 4]]
B transpose:
 [[1 3 5]
 [2 4 6]]
