<a href="https://colab.research.google.com/github/20KMJ/ESAA7/blob/main/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [101]:
!pip install generators

import numpy as np

import generators as ge


def question(n):
    print(f'{n}. ' + ge.QHA[f'q{n}'])


def hint(n):
    print(ge.QHA[f'h{n}'])


def answer(n):
    print(ge.QHA[f'a{n}'])


def pick():
    n = np.random.randint(1, 100)
    question(n)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [103]:
# run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [109]:
print('numpy version:',np.__version__)

numpy version: 1.21.6


In [110]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆)

In [113]:
x3 = np.zeros(10)
print(x3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [21]:
print(x.itemsize)

8


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [24]:
x5 = np.zeros(10)
x5[4]=1
print(x5)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
x6 = np.arange(10,50)
print(x6)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [31]:
print(np.flip(x6))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [35]:
x8 = np.arange(0,9).reshape(3,3)
print(x8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [47]:
x10 = np.identity(3)
print(x10)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [49]:
x11 = np.random.random((3,3,3))
print(x11)

[[[0.03451342 0.31780272 0.03723675]
  [0.19619866 0.91574755 0.52568037]
  [0.26135949 0.82712342 0.57645702]]

 [[0.86018902 0.62759551 0.39266718]
  [0.66587662 0.36053466 0.72303013]
  [0.89854588 0.81851033 0.55412885]]

 [[0.42147861 0.23469314 0.91579991]
  [0.5451457  0.22434083 0.41953349]
  [0.55504585 0.96228295 0.92750908]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [52]:
x12 = np.random.random((10,10))
print(x12)

[[0.74223806 0.11036507 0.64431133 0.20090463 0.61016576 0.53817789
  0.62795651 0.0331985  0.0974265  0.60360093]
 [0.14594763 0.02845151 0.54066438 0.07615199 0.96354979 0.43327187
  0.54199066 0.36552341 0.24650492 0.55437441]
 [0.4847479  0.0717706  0.14779711 0.41533526 0.11301523 0.2157291
  0.16540823 0.39114751 0.98446937 0.68308546]
 [0.26908031 0.00669236 0.41641636 0.97087391 0.0623738  0.76090095
  0.32095117 0.84833316 0.72856057 0.46557682]
 [0.32362455 0.18513667 0.05975689 0.96727251 0.47435595 0.66752778
  0.56052052 0.65455618 0.83984695 0.3892345 ]
 [0.84405175 0.86648038 0.75273862 0.69807039 0.86132782 0.89345532
  0.73642721 0.61287355 0.9729199  0.54160034]
 [0.35309408 0.60550778 0.82353754 0.41630585 0.11701205 0.36523366
  0.33114407 0.76327169 0.01123135 0.57698065]
 [0.6280733  0.01261898 0.49450729 0.1425597  0.70050473 0.84390907
  0.72244726 0.00460043 0.64306244 0.36010767]
 [0.09737988 0.09005894 0.0966434  0.14327644 0.27171785 0.24968978
  0.32830207 

In [53]:
print(x12.min(), x12.max())

0.0046004272680917335 0.9844693729282844


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [56]:
x13 = np.random.random(30)
print(x13)

[0.07931062 0.38990247 0.55246055 0.6182968  0.25838524 0.97489208
 0.6267173  0.13008523 0.99309364 0.81972076 0.50794527 0.07694913
 0.78495999 0.5884998  0.04862651 0.51263254 0.80994739 0.41565661
 0.81338468 0.57870509 0.77295562 0.24787991 0.04883308 0.84756987
 0.67382328 0.50048623 0.76492291 0.0112566  0.09128782 0.19325661]


In [58]:
np.mean(x13)

0.4910814548126095

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [64]:
x14 = np.ones((5,5))
print(x14)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
x14[1:-1,1:-1] = 0
print(x14)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [68]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [71]:
x16 = np.diag(1+np.arange(4),k=-1)
print(x16)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [79]:
x17 = np.zeros((8,8),dtype=int)
x17[1::2,::2] = 1
x17[::2,1::2] = 1
print(x17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [82]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [83]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.48648196  1.24154747  1.72683998  1.33887959  1.52569163]
 [-0.23947041 -1.44253795  0.24972575 -0.4176362  -0.35048982]
 [-0.99745583 -1.16598381 -0.4929814  -0.1165293  -0.32742797]
 [ 1.33306349 -0.64846744 -0.40693768  1.08627856 -1.02783098]
 [-0.88574462 -1.16164914 -1.24677654  0.78688357  0.15252709]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [84]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [85]:
x21 = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x21)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [86]:
x22 = np.arange(11)
x22[(3 < x22) & (x22 < 8)] *= -1
print(x22)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [87]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [96]:
Z = [0,1,2]
Z<Z>Z

False

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [97]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [98]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [99]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3